### 1. Importing Numpy

In [9]:
import numpy as np

### 2. Creating Arrays

In [10]:
# From lists
a = np.array([1, 2, 3])                # 1D
b = np.array([[1, 2], [3, 4]])         # 2D
c = np.array([[[1], [2]], [[3], [4]]]) # 3D tensor
 
# Zeros / Ones / Random
zeros = np.zeros((2, 3))              # 2x3 of zeros
ones = np.ones((3, 1))                # 3x1 of ones
rand = np.random.rand(2, 2, 2)        # 3D random tensor

# Ranges
arange = np.arange(0, 10, 2)          # [0, 2, 4, 6, 8]
linspace = np.linspace(0, 1, 5)       # [0. , 0.25, ..., 1.]

In [12]:
print('Zeroes', zeros)
print('Ones', ones)
print('Random', rand)
print('Arange', arange)
print('Linspace', linspace)

Zeroes [[0. 0. 0.]
 [0. 0. 0.]]
Ones [[1.]
 [1.]
 [1.]]
Random [[[0.29394361 0.89614207]
  [0.5431233  0.59465888]]

 [[0.22572237 0.60329077]
  [0.3176353  0.9366115 ]]]
Arange [0 2 4 6 8]
Linspace [0.   0.25 0.5  0.75 1.  ]


In [6]:
print(a, b, c)
print(zeros, ones, rand)
print(arange, linspace)

[1 2 3] [[1 2]
 [3 4]] [[[1]
  [2]]

 [[3]
  [4]]]
[[0. 0. 0.]
 [0. 0. 0.]] [[1.]
 [1.]
 [1.]] [[[0.96969859 0.54246157]
  [0.7282583  0.94484446]]

 [[0.48850549 0.86990744]
  [0.6471516  0.02250084]]]
[0 2 4 6 8] [0.   0.25 0.5  0.75 1.  ]


### 3. Inspecting Arrays

In [13]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a.shape)   # (2, 3)
print(a.ndim)    # 2 (number of dimensions)
print(a.size)    # 6 (total elements)
print(a.dtype)   # data type, e.g., int64
print(a.itemsize) # size in bytes of each element

(2, 3)
2
6
int64
8


In [ ]:
# Slicing and indexing
print(a[0, 1])          # 2 (element at row 0, column 1)
print(a[:, 1])          # [2, 5] (all rows, column 1)
print(a[1, :])          # [4, 5, 6] (row 1, all columns)
print(a[0:2,:2])      # [[1, 3], [4, 6]] (first two rows, every second column)

[[1 2]
 [4 5]]


### 4. Element-wise Operations

In [9]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

print(x + y)      # [11, 22, 33]
print(x * 2)      # [2, 4, 6]
print(x ** 2)     # [1, 4, 9]
print(np.exp(x))  # e^x for each element
print(np.sqrt(x)) # square root

[11 22 33]
[2 4 6]
[1 4 9]
[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]


In [18]:
# Math operations
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [23]:
# Basic operations

add = np.add(list1, list2)          # Element-wise addition
subtract = np.subtract(list1, list2) # Element-wise subtraction
multiply = np.multiply(list1, list2) # Element-wise multiplication
divide = np.divide(list1, list2)     # Element-wise division

In [24]:
print ('Addition:', add)
print ('Subtraction:', subtract)
print ('Multiplication:', multiply)
print ('Division:', divide)

Addition: [1.32912742 0.71387729 0.75053257 0.77504061 1.38652949 1.33257103
 1.41548309 0.48494962 0.90993206 0.87225928]
Subtraction: [-0.59465614  0.1415687   0.41640502  0.61689088  0.54554791  0.48083215
 -0.19673218  0.13829554  0.57031173  0.78329446]
Multiplication: [0.35324094 0.12239477 0.0974765  0.0550334  0.40621038 0.38613649
 0.49122221 0.05401262 0.12568022 0.03682151]
Division: [ 0.38178478  1.49472855  3.49249139  8.80135225  2.2974075   2.12906002
  0.755948    1.79788785  4.35852527 18.60908403]


In [25]:
type(list1)

numpy.ndarray

In [26]:
list1

array([0.36723564, 0.42772299, 0.58346879, 0.69596575, 0.9660387 ,
       0.90670159, 0.60937545, 0.31162258, 0.74012189, 0.82777687])

In [27]:
list1.T # Transpose (not applicable for 1D arrays, but shown for completeness)

array([0.36723564, 0.42772299, 0.58346879, 0.69596575, 0.9660387 ,
       0.90670159, 0.60937545, 0.31162258, 0.74012189, 0.82777687])

In [28]:
dot = np.dot(list1, list2)  # Dot product
print('Dot product:', dot)

Dot product: 2.12822903513489


### 5. Broadcasting

In [10]:
a = np.array([[1], [2], [3]])  # shape (3, 1)
b = np.array([10, 20, 30])     # shape (3,)

result = a * b  # shape (3, 3) -- broadcasted

### 6. Reshape, Flatten, Transpose

In [4]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a.reshape(3, 2))    # shape becomes (3, 2)
print(a.flatten())        # [1 2 3 4 5 6]
print(f'Transposed array: {a.T}')                # transpose

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
Transposed array: [[1 4]
 [2 5]
 [3 6]]


### 7. Stacking and Concatenation

In [5]:
a = np.array([[1, 2]])
b = np.array([[3, 4]])

print(np.vstack((a, b)))   # Vertical stack → [[1, 2], [3, 4]]
print(np.hstack((a, b)))   # Horizontal → [[1, 2, 3, 4]]

[[1 2]
 [3 4]]
[[1 2 3 4]]


### 8. Saving and Loading

In [6]:
# Save/load in .npy (binary)
np.save('array.npy', a)
a_loaded = np.load('array.npy')

# Save/load in text
np.savetxt('array.txt', a)
a_txt = np.loadtxt('array.txt')

### 9. Type Casting

In [7]:
a = np.array([1.2, 3.4, 5.6])
a_int = a.astype(int)  # [1 3 5]

### 10. Stat Functions

In [29]:
sqrt = np.sqrt(25)    # 5.0
abs_value = np.abs(-10)  # 10
power = np.power(2, 3)  # 8 (2 raised to the power of 3)
log = np.log(10)      # Natural logarithm of 10
exp = np.exp(2)      # e^2
mins = np.min(list1)        # 1.2
maxs = np.max(list1)        # 9.8


In [30]:
print('Square root:', sqrt)
print('Absolute value:', abs_value)
print('Power:', power)
print('Logarithm:', log)
print('Exponential:', exp)
print('Minimum:', mins)
print('Maximum:', maxs)

Square root: 5.0
Absolute value: 10
Power: 8
Logarithm: 2.302585092994046
Exponential: 7.38905609893065
Minimum: 0.3116225769776225
Maximum: 0.9660386971442769


In [31]:
list1.sort()  # Sorts in place
print('Sorted list1:', list1)

Sorted list1: [0.31162258 0.36723564 0.42772299 0.58346879 0.60937545 0.69596575
 0.74012189 0.82777687 0.90670159 0.9660387 ]


### 11. Deleting Arrays

In [36]:
np.delete(list1, -1)  # Deletes the first element
print('After deletion:', list1)

After deletion: [0.31162258 0.36723564 0.42772299 0.58346879 0.60937545 0.69596575
 0.74012189 0.82777687 0.90670159 0.9660387 ]
