### 1. Importing Numpy

In [2]:
import numpy as np

### 2. Creating Arrays

In [5]:
# From lists
a = np.array([1, 2, 3])                # 1D
b = np.array([[1, 2], [3, 4]])         # 2D
c = np.array([[[1], [2]], [[3], [4]]]) # 3D tensor

# Zeros / Ones / Random
zeros = np.zeros((2, 3))              # 2x3 of zeros
ones = np.ones((3, 1))                # 3x1 of ones
rand = np.random.rand(2, 2, 2)        # 3D random tensor

# Ranges
arange = np.arange(0, 10, 2)          # [0, 2, 4, 6, 8]
linspace = np.linspace(0, 1, 5)       # [0. , 0.25, ..., 1.]

In [6]:
print(a, b, c)
print(zeros, ones, rand)
print(arange, linspace)

[1 2 3] [[1 2]
 [3 4]] [[[1]
  [2]]

 [[3]
  [4]]]
[[0. 0. 0.]
 [0. 0. 0.]] [[1.]
 [1.]
 [1.]] [[[0.96969859 0.54246157]
  [0.7282583  0.94484446]]

 [[0.48850549 0.86990744]
  [0.6471516  0.02250084]]]
[0 2 4 6 8] [0.   0.25 0.5  0.75 1.  ]


### 3. Inspecting Arrays

In [8]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a.shape)   # (2, 3)
print(a.ndim)    # 2 (number of dimensions)
print(a.size)    # 6 (total elements)
print(a.dtype)   # data type, e.g., int64
print(a.itemsize) # size in bytes of each element

(2, 3)
2
6
int64
8


### 4. Element-wise Operations

In [9]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

print(x + y)      # [11, 22, 33]
print(x * 2)      # [2, 4, 6]
print(x ** 2)     # [1, 4, 9]
print(np.exp(x))  # e^x for each element
print(np.sqrt(x)) # square root

[11 22 33]
[2 4 6]
[1 4 9]
[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]


### 5. Broadcasting

In [10]:
a = np.array([[1], [2], [3]])  # shape (3, 1)
b = np.array([10, 20, 30])     # shape (3,)

result = a * b  # shape (3, 3) -- broadcasted